version: '3.9'
services:
  web:
    image: imse_m3
    container_name: web_service
    volumes:
      - nodes:/node_modules/
    build: .
    ports:
      - '3000:3000' 
    #network_mode: host
    depends_on: 
      - db
    #networks:
      #- app-network
    #restart: always
    #environment: 
      #- MONGO_URL=mongodb://db:27017/mydb
  db:
    image: mongo:latest
    #network_mode: host
    ports:
      - 27017:27017
    #networks:
      #- app-network
    volumes: 
      - db_data:/data/
    #restart: always

#networks:
  #app-network:
    #driver: bridge
    
volumes:
    db_data: {}
    nodes: {}